version: '3.9'
services:
  ministack:
    image: ministackorg/ministack
    ports:
      - '4566:4566'
    environment:
      MINISTACK_REGION: us-east-1
      PERSIST_STATE: 1
      S3_PERSIST: 1
      STATE_DIR: /data/ministack-state
      S3_DATA_DIR: /data/s3
    volumes:
      - ./scripts/ministack-init.sh:/etc/localstack/init/ready.d/init.sh
      - ministack-data:/data

volumes:
  ministack-data:
